# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39c78d9bcfc929d0880ec6221e41a3ea4c0ab297c2194cb16e93469a5888a5cb079c40c0dd6060486b0a2841805db2c9364d65fa73fc501dc55c73ae9fa9c6c

test:
  secret_key_base: 610e92105651ba6b97f44d7510f51684255a58fa0860273976d17b8f3029d47a56df3c77dab5cf5cc5857919e5dc43d1a8341c15e98ad112e27c3a02faf14c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
